apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# all resources live in this namespace
namespace: minio-dev

resources:
  - namespace.yaml
  - tenant-config.yaml
  - storage-user.yaml
  - tenant.yaml
  - pv-dev-data0.yaml