# tenant.yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-dev
  namespace: minio-dev
spec:
  configuration:
    name: storage-configuration
  requestAutoCert: false
  exposeServices:
    minio:   true
    console: true
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      # <— erasureCoding section removed entirely
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
