apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# all resources live in this namespace
namespace: minio-prod

resources:
  - namespace.yaml
  - tenant-config.yaml
  - storage-user.yaml
  - tenant.yaml
  - pv-pool0-0-data0.yaml
  - pv-pool0-0-data1.yaml
  - pv-pool0-1-data0.yaml
  - pv-pool0-1-data1.yaml