apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pool0-1-data1
spec:
  capacity:
    storage: 15Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-storage
  local:
    path: /mnt/kvaltko/prod/minio/data1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["k3s-05"]
  persistentVolumeReclaimPolicy: Retain
